- name: Installs nginx web server
  apt: pkg=nginx state=present update_cache=true
  notify:
    - start nginx
- name: Installs httpd web server
  apt: pkg=apache2 state=latest update_cache=true
  notify:
    - restart apache

- name: Upload default index.html for host
  copy: src=static_files/index.html dest=/usr/share/nginx/www/ mode=0644
- name: Create content
  copy:
    src: static_files/index.html
    dest: /var/www/html/index.html
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache
- name: apache2 listen on port 8081
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
  notify:
    - restart apache



  